### ISSUE TITLE
Съехало меню отображения

### ISSUE THREAD

**Issue by teleportx** [feytox/SPwallet#3]
![изображение](https://user-images.githubusercontent.com/77507478/181591868-327bbdf2-5b7e-426b-82f8-eee1e54f96ef.png)
Как-то странно выглядит отображение аров с карты.

**Comment by feytox** [comment]
Уже исправлено в версии 1.2.3: до этого подсасывались старые настройки с версии 1.1.3, где смещение было другое.
Если по какой-то причине не исправляется, просто ресетайте в конфиге данные пункты
![image](https://user-images.githubusercontent.com/73577753/181618013-e353b3df-c81b-408f-9e95-4c682e8d046b.png)

**Comment by teleportx** [comment]
Спасибо, помогло
