### ISSUE TITLE
Вылетает майнкрафт при открытии инвентаря

### ISSUE THREAD

**Issue by teleportx** [feytox/SPwallet#4]
Есть проблемка на версии `1.19.2`
Версия мода `v.2.0.1`
При открытии инвентаря майнкрафт вылетает с ошибкой `ClassNotFoundException`

Я думаю это из-за того, что библиотека LibNinePatch не добавлена в конечную сборку мода
Логи - https://pastebin.pl/view/98837a84

**Comment by feytox** [comment]
Странно, что данный баг не был замечен ни мною, ни тестером, ни другими игроками до этого момента.
В любом случае, баг исправлен в новой версии `v.2.0.2`.
